version: '3.1'

services:
  # server:
  #   # image: node:18-alpine
  #   # restart: always
  #   build:
  #     context: ./apps/server
  #     dockerfile: Dockerfile
  #   # command: pnpm --filter server dev
  #   volumes:
  #     # - ./node_modules:/habits-tracker/node_modules
  #     - ./apps/server:/habits-tracker/apps/server
  #   environment:
  #     # Node
  #     NODE_ENV: development
  #     # Web Push Notifications
  #     WEB_PUSH_SUBJECT: http://192.168.0.12:3333
  #     WEB_PUSH_PUBLIC_KEY: BIsfJ8LVIbSsPzTeRpChlLEFMxHXz-QyNmydjhRZmEJRGHAeJd_5K1gynTtblBNHriY_-cic0xBz6F_pNq-XfVY
  #     WEB_PUSH_PRIVATE_KEY: VE3xm2xMEdXWIiH9d43X1_o7nYb3khkaN6kSZJ_-g0M
  #     # Prisma
  #     #PRISMA_DATABASE_URL=file:./dev.db
  #     PRISMA_DATABASE_URL: postgres://postgres:example@localhost/habits-tracker
  #     # Firebase Admin Credentials
  #     FIREBASE_TYPE: service_account
  #     FIREBASE_PROJECT_ID: habits-tracker-5f7a4
  #     FIREBASE_PRIVATE_KEY_ID: 5437af0bcf636a43d21075512e854aaa402f33c7
  #     FIREBASE_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDdrzXdO4esYwjG\nu1AP21FAF5LsNGCLxH5aWoj3Ssu7m8lVDbtT/5qMeFOkrMujWs6rgIBiDTRxdLrg\nVGpwvuuLWiw8wh/1wVU4rnMe1xnWcNcSkFZ/OdSA6UlI+4caU0Z6aQVJ2jXI4nNL\nyt3IgjH70Ns+aoJdnf2fLXt/AbQURepWIfU559yfvBovfnc4zHBoj+qgfGGDe4M7\nwIzPp0dnGzdGWoCjUx6MLTVCFu/7AyWGiODZRki+05a0WGl61XMimaOiRpnsXOHY\nfYf9RlPLCSIhBJapcudfzEPcF2xcSSyZH8B5Q9e0qrHyu4TwOXMQWJbmJNJRBMqV\nK0ImSFupAgMBAAECggEALppLA0lktfFy0p5lkBPNwqDCDvxa0H8cBeAS+5OifTvc\niRAUMa4h/gY8pTl7LMnl+QlQU+yNOg2tTIQKhU2phDfOZW503AvK39nSkyjqgllh\n6UHlISVV3kzMjnZsGjVn80tZJIOmO2cZkFUjJyfxnIu1T2uCIO6Z9ujPla1Uv07o\nLH2JigJTYXX83MSRh+qjeT3+dF/Fs08EsX+vJtjWvqLCcVSTwNxTCFwtF4d8HQrT\nwg3YfpnRcXHvrMFEa9bxhrOw29Nyto2WQRNOGZiMi+TTxXud8wgQ2mRsbbT+v00Y\nJz/3i5WKjXxkdXvdUna+/C/1sfA4wNY+1aUOapyttQKBgQDy8FBoD6Da0BuDbSq+\nrIjCOfLa/ocgPPf+iN7Eik3oYXBVfOcVN0/YFXMZbzS5U6hbdO+YTLgS47d1WqEC\nF2PIwvgJMVnjCVlNc+AHVxW/JF0fyQtbMqK5lkb9p64f0eX/yNJmvb8mrJ6OQz1R\nd4HnRFN/i+lpVGrEW/oV7ApkLQKBgQDpmlza9bQ1BUT8cNlcm42+OrOIFFc0iVLW\n/ZmRVaP23pTgJAs8roJmzkwK/DiZp5oZh4vw6mw3B+qapWBKiyZ1wMs14OUWBfbv\nGXwtolhl2t+6L7zaedioo3vr/pUiHSQpcH1jGxg2BbiboWb8vRvqCvcbNcInZelZ\nfj9AbBzW7QKBgA26BGEM2QLkFVnktjCV4RhQW+eB0DLDHyQTqbqjMem6b7V03D23\npVxJQfqi7PC3yGB6h/ssAo6WrUwFNem/VpUGZytlzXVlltUogfUIN6NYM6bTHkAl\n6UnhMtusOMt1ebBtMW46tG1D/aV+KR3MSdu+YZVoW2TnLy0vIT9R2fh1AoGAerPS\nQlD9LzxtWAwOoE40zc8XrkrA45+eG79pgqVxUqLnoDROkrk3VbjWyI5jTJJ0pyRD\npW/9F4rY+BIV2hHtSbzTAKH4svC/HChOycmUlSu6iJm6oSePXkVBOlynCRw1em7T\n7dK1jOrEZTsKVYcfune4BFrgeMFXKOLfZn9jRqECgYAaVi0WoNxU2uw3bCEhxZxl\nrPMb8UebgQ2UKEVHD3Drq1kNSwKVT0Nv0HaoO71J3wqAM9FHfmxSbSc0ifOEVLxV\nyQEU4PrmTbX/Q69aM2x4veizpYMk4YU+ypu4HuFnZh0xJ61IkYg7MpIDjCPaAWbb\nLMVAEXgc5c/I8VpSyBpNNw==\n-----END PRIVATE KEY-----\n
  #     FIREBASE_CLIENT_EMAIL: firebase-adminsdk-t5etw@habits-tracker-5f7a4.iam.gserviceaccount.com
  #     FIREBASE_CLIENT_ID: 108000143347000515504
  #     FIREBASE_AUTH_URI: https://accounts.google.com/o/oauth2/auth
  #     FIREBASE_TOKEN_URI: https://oauth2.googleapis.com/token
  #     FIREBASE_AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
  #     FIREBASE_CLIENT_X509_CERT_URL: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-t5etw%40habits-tracker-5f7a4.iam.gserviceaccount.com
  #     FIREBASE_DATABASE_URL: https://habits-tracker-5f7a4-default-rtdb.firebaseio.com/
  #   ports:
  #     - '80:3333'
  # web:
  #   # image: node:18-alpine
  #   # restart: always
  #   build: .docker/Dockerfile.web.development
  #   # command: pnpm --filter web dev
  #   # volumes:
  #   # - ./node_modules:/habits-tracker/node_modules
  #   # - ./apps/web:/habits-tracker/apps/web
  #   environment:
  #     VITE_API_HOST: http://localhost:3333
  #     VITE_API_KEY: AIzaSyB-hKcUxF3jVv1EsQ9K4ZQ3-w3nuyyxUGw
  #     VITE_AUTH_DOMAIN: habits-tracker-5f7a4.firebaseapp.com
  #     VITE_DATABASE_URL: https://habits-tracker-5f7a4-default-rtdb.firebaseio.com
  #     VITE_PROJECT_ID: habits-tracker-5f7a4
  #     VITE_STORAGE_BUCKET: habits-tracker-5f7a4.appspot.com
  #     VITE_MESSAGING_SENDERID: 548313913770
  #     VITE_APP_ID: 1:548313913770:web:a795b3bac12e64e1bcb3d3
  #     VITE_MEASUREMENT_ID: G-ECT18B5XCC
  #   ports:
  #     - '3000:5173'
  # db:
  #   image: postgres:14.2-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_USER: habits-tracker
  #     # POSTGRES_PASSWORD: habits-tracker123
  #     # POSTGRES_DB: postgres # dbname
  #   ports:
  #     - '5432:5432'
