version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.web.development
    ports:
      - '3000:5173'
    env_file:
      - 'apps/web/.env'
    volumes:
      - ./apps/web/.env:/habits-tracker/apps/web/.env
      - ./apps/web/:/habits-tracker/apps/web/
      - ./node_modules/:/habita-tracker/node_modules
    depends_on:
      - server
    #   - db
  server:
    container_name: server
    build: 
      context: .
      dockerfile: ./.docker/Dockerfile.server.development
    ports:
      - '3333:3333'
    env_file:
      - 'apps/server/.env'
    volumes:
      - ./apps/server/.env:/habits-tracker/apps/server/.env
      - ./apps/server/:/habits-tracker/apps/server/
      - ./node_modules/:/habita-tracker/node_modules
    depends_on:
       - db
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: habits-tracker
      POSTGRES_PASSWORD: habits-tracker123
      # POSTGRES_DB: postgres # dbname
    ports:
      - '5432:5432'
