FROM node:18-alpine

WORKDIR /habits-tracker

ADD pnpm-workspace.yaml .
ADD pnpm-lock.yaml .
ADD package.json .
ADD tsconfig.json .

COPY ./apps ./apps

RUN npm i -g pnpm
RUN pnpm -v
RUN pnpm install

# COPY ./apps/web ./apps/web

CMD ["bash"]